spring.application.name=Lecture3

server.port=8081

spring.ai.openai.api-key=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

